"""Bake a compact metric distance field from the mapped Weiming Lake outline.

This describes distance to the mapped outer bank, not surveyed water depth.
The generated field does not change the water mesh or infer submerged features.
"""
from pathlib import Path
import base64
import hashlib
import json
import math

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'src/water-detail.js'
WIDTH, HEIGHT, RANGE = 512, 384, 8.0


def build():
    source_script = (ROOT / 'src/data.js').read_text()
    if not source_script.startswith('YY.CAMPUS='):
        raise ValueError('Review the published campus data format before baking water detail')
    campus = json.JSONDecoder().raw_decode(source_script[len('YY.CAMPUS='):])[0]
    lake = next(f for f in campus['features'] if f['properties']['id'] == 'way/838526031')
    ring = lake['geometry']['coordinates'][0]
    source = hashlib.sha256(json.dumps([ring, WIDTH, HEIGHT, RANGE], separators=(',', ':')).encode() + Path(__file__).read_bytes()).hexdigest()
    if OUTPUT.exists() and f'"sourceHash":"{source}"' in OUTPUT.read_text():
        return
    xmin, zmin = min(p[0] for p in ring) - RANGE, min(p[1] for p in ring) - RANGE
    xmax, zmax = max(p[0] for p in ring) + RANGE, max(p[1] for p in ring) + RANGE
    sx, sz = (xmax-xmin)/WIDTH, (zmax-zmin)/HEIGHT
    field = [RANGE*RANGE] * (WIDTH*HEIGHT)
    for a, b in zip(ring, ring[1:] + ring[:1]):
        dx, dz = b[0]-a[0], b[1]-a[1]
        length = dx*dx + dz*dz
        if not length:
            continue
        x0, x1 = max(0, math.floor((min(a[0],b[0])-RANGE-xmin)/sx)), min(WIDTH-1, math.ceil((max(a[0],b[0])+RANGE-xmin)/sx))
        z0, z1 = max(0, math.floor((min(a[1],b[1])-RANGE-zmin)/sz)), min(HEIGHT-1, math.ceil((max(a[1],b[1])+RANGE-zmin)/sz))
        for row in range(z0,z1+1):
            z = zmin+(row+.5)*sz
            for col in range(x0,x1+1):
                x = xmin+(col+.5)*sx
                t = min(1.,max(0.,((x-a[0])*dx+(z-a[1])*dz)/length))
                d = (x-a[0]-t*dx)**2+(z-a[1]-t*dz)**2
                i = row*WIDTH+col
                if d < field[i]:
                    field[i] = d
    raw = bytes(round(math.sqrt(d)/RANGE*255) for d in field)
    packed = bytearray()
    i = 0
    while i < len(raw):
        count = 1
        while i+count < len(raw) and count < 255 and raw[i+count] == raw[i]:
            count += 1
        packed.extend((count,raw[i]))
        i += count
    data = dict(sourceHash=source,feature='way/838526031',width=WIDTH,height=HEIGHT,range=RANGE,
                bounds=[xmin,zmin,1/(xmax-xmin),1/(zmax-zmin)],rle=base64.b64encode(packed).decode())
    OUTPUT.write_text('// Generated by tools/build-water-detail.py from the public mapped outer bank.\n'
                      '// Not bathymetry; internal island banks retain their existing appearance.\nYY.WATER_SHORE='+json.dumps(data,separators=(',',':'))+';\n')
    print('Water-bank field:',len(raw),'decoded bytes;',len(packed),'packed bytes')


if __name__ == '__main__':
    build()
