/* Dormitory 30: own north-up plans; labelled photo end has unresolved compass direction; south canopy remains unknown. */
(function(Y){'use strict';
const F=Y.Footprints,G=Y.Geo,A=Y.Architecture30,previous=A.render,ID='way/240832246';
const O=[-91.023,566.698],R=Math.atan2(2.721,65.752),CO=Math.cos(R),SI=Math.sin(R);
const C={wall:'#747b77',frame:'#e4e5dc',glass:'#718b91',roof:'#727e78',tile:'#929e96',stone:'#a8afa5',door:'#526762'};
const H={floor:3.2,wall:19.2,eave:19.4,ridge:22.5},entrances=[{name:'main-south',u:31.40,v:19.577,face:'south',axis:0,outward:1,width:6.8,sill:.6},{name:'north-west-stair',u:15.72,v:-1.15,face:'north-stair',axis:0,outward:-1,width:1.9,sill:.3},{name:'north-east-stair',u:46.59,v:-1.15,face:'north-stair',axis:0,outward:-1,width:1.9,sill:.3},{name:'west-end',u:0,v:9.75,face:'west',axis:1,outward:-1,width:1.9,sill:.3},{name:'east-end',u:65.810,v:9.75,face:'east',axis:1,outward:1,width:1.9,sill:.3}];
const world=(u,v)=>[O[0]+u*CO+v*SI,O[1]-u*SI+v*CO],local=p=>[(p[0]-O[0])*CO-(p[1]-O[1])*SI,(p[0]-O[0])*SI+(p[1]-O[1])*CO];
function clip(p,a,k,greater){const out=[];for(let i=0;i<p.length;i++){const s=p[i],e=p[(i+1)%p.length],si=greater?s[a]>=k:s[a]<=k,ei=greater?e[a]>=k:e[a]<=k;if(si)out.push(s);if(si!==ei){const t=(k-s[a])/(e[a]-s[a]);out.push(s.map((x,j)=>x+t*(e[j]-x)));}}return out;}
function pieces(f,box){const out=[];for(const pg of F.polygons(f.geometry))for(const tri of F.capTriangles(pg)){let p=tri.map(local);for(const [a,k,g] of [[0,box[0],true],[0,box[2],false],[1,box[1],true],[1,box[3],false]])if(p.length)p=clip(p,a,k,g);if(p.length>=3&&Math.abs(F.area([...p,p[0]]))>1e-8)out.push(p);}return out;}
function render(b,f,add){const id=f.properties.pickId;b.id=id;const vertex=(u,y,v)=>{const p=world(u,v);return[p[0],y,p[1]];};
 function group(name,fn){const old=b.e.add;b.e.add=function(k,...args){return old.call(this,'038-'+name+'-'+k,...args);};try{fn();}finally{b.e.add=old;}}
 // The full source footprint gets only a roof-level cap; facade apertures are built as actual openings.
 add('038-source-roof-deck',F.surface(f.geometry,H.wall),C.roof,24,id);
 const roofSpecs=[{name:'long-independent',box:[-.02,-.02,65.812,19.582],axis:0,rise:3.1}];
 for(const q of roofSpecs){const a=q.axis,c=1-a,box=q.box,amin=box[a],amax=box[a+2],cmin=box[c],cmax=box[c+2],cmid=(cmin+cmax)/2,hip=(cmax-cmin)*.42,r0=amin+hip,r1=amax-hip;
  const xyz=(u,v)=>a===0?[u,v]:[v,u],height=p=>{const along=p[a],across=p[c],t=Math.min(1,Math.max(0,Math.min((along-amin)/hip,(amax-along)/hip,1-Math.abs(across-cmid)/((cmax-cmin)/2))));return H.eave+q.rise*t;};
  const surfaces=[{p:[xyz(amin,cmin),xyz(amax,cmin),xyz(r1,cmid),xyz(r0,cmid)]},{p:[xyz(r0,cmid),xyz(r1,cmid),xyz(amax,cmax),xyz(amin,cmax)]},{p:[xyz(amin,cmin),xyz(r0,cmid),xyz(amin,cmax)]},{p:[xyz(r1,cmid),xyz(amax,cmin),xyz(amax,cmax)]}],mesh=new G.Geometry(),seams=new G.Geometry();
  for(const sf of surfaces){for(const tri of pieces(f,box)){let p=tri;const poly=sf.p,sign=Math.sign(F.area([...poly,poly[0]]));for(let i=0;i<poly.length&&p.length;i++){const aa=poly[i],cc=poly[(i+1)%poly.length],out=[];const d=s=>sign*((cc[0]-aa[0])*(s[1]-aa[1])-(cc[1]-aa[1])*(s[0]-aa[0]));for(let j=0;j<p.length;j++){const s=p[j],e=p[(j+1)%p.length],ds=d(s),de=d(e),si=ds>=-1e-8,ei=de>=-1e-8;if(si)out.push(s);if(si!==ei){const t=ds/(ds-de);out.push(s.map((x,k)=>x+t*(e[k]-x)));}}p=out;}for(let j=1;j<p.length-1;j++)mesh.tri(...[p[0],p[j],p[j+1]].map(p=>vertex(p[0],height(p),p[1])));}}
  add('038-hip-roof-'+q.name,mesh,C.roof,2,id);
  // Sparse tile seams are clipped into each triangular roof plane, leaving the mapped recesses open.
  for(let s=amin+.2;s<amax;s+=.45){const rr=box.slice();rr[a]=s-.025;rr[a+2]=s+.025;for(let j=0;j<24;j++){rr[c]=cmin+(cmax-cmin)*j/24;rr[c+2]=cmin+(cmax-cmin)*(j+1)/24;for(const p of pieces(f,rr))for(let k=1;k<p.length-1;k++)seams.tri(...[p[0],p[k],p[k+1]].map(p=>vertex(p[0],height(p)+.035,p[1])));}}
  add('038-roof-tile-seams-'+q.name,seams,C.tile,2,id);
 }
 const map=x=>(x-234)/(1655-234)*65.810,cells=(xs,ratio=.68)=>xs.slice(1).map((x,i)=>[xs[i],x,ratio]),south=cells([234,309,384,458,533,608,682,757,832,906,981,1056,1130,1205,1280,1355,1430,1505,1580,1655].map(map)),north=cells([234,309,384,458,533,610,684,759,833,908,982,1057,1131,1205,1280,1355,1428,1503,1579,1655].map(map));
 const stairCentres=[15.72,46.59],stairWidth=3.55;
 const rawRing=F.polygons(f.geometry)[0][0],pts=rawRing.slice(0,-1),simple=pts.filter((p,i)=>{const a=pts[(i+pts.length-1)%pts.length],c=pts[(i+1)%pts.length];return Math.abs((c[0]-a[0])*(p[1]-a[1])-(c[1]-a[1])*(p[0]-a[0]))/Math.hypot(c[0]-a[0],c[1]-a[1])>.02;}),ring=[...simple,simple[0]],positive=F.area(ring)>0;
 for(let i=1;i<ring.length;i++){let a=ring[i-1],c=ring[i];if(positive)[a,c]=[c,a];const la=local(a),lc=local(c),dx=c[0]-a[0],dz=c[1]-a[1],len=Math.hypot(dx,dz),du=lc[0]-la[0],dv=lc[1]-la[1],horizontal=Math.abs(du)>Math.abs(dv),mx=(la[0]+lc[0])/2,mv=(la[1]+lc[1])/2,face=horizontal?(mv>10?'south':'north'):(mx<1?'west':'east'),source=horizontal?(face==='south'?south:north):face==='east'?cells([7.8,11.7],.32):cells([0,6.6,12.9,19.582],.32),axis=horizontal?0:1,delta=horizontal?du:dv,balcony=face==='south',setback=balcony?1.1:0;
 const positions=source.map(([s,e,ratio])=>{const t0=(s-la[axis])/delta*len,t1=(e-la[axis])/delta*len,mid=(t0+t1)/2,w=Math.abs(t1-t0)*ratio;return[mid-w/2,mid+w/2];}).filter(([s,e])=>s>.1&&e<len-.1&&e-s>.3).sort((a,b)=>a[0]-b[0]);
 const towerCuts=face==='north'?stairCentres.map(u=>{const x=(u-la[0])/du*len;return[x-stairWidth/2,x+stairWidth/2];}):[];
 b.local(a[0],0,a[1],Math.atan2(-dz,dx),()=>group('facade-'+face,()=>{
 for(let floor=0;floor<6;floor++){const base=floor*3.2,col=floor===5?C.frame:C.wall,panel=(s,e,lo,hi)=>{let ranges=[[s,e]];for(const [cs,ce] of towerCuts)ranges=ranges.flatMap(([s,e])=>[[s,Math.min(e,cs)],[Math.max(s,ce),e]]).filter(([s,e])=>e>s);for(const [s,e] of ranges)if(e>s&&hi>lo)b.box((s+e)/2,(lo+hi)/2,-setback-.035,e-s,hi-lo,.07,col,24);};
 let openings=positions.filter(([s,e])=>!towerCuts.some(([cs,ce])=>e>cs&&s<ce)).map(([s,e])=>({s,e,bottom:base+.85,top:base+2.65})),doorIntervals=[];if(floor===0)for(const door of entrances.filter(q=>q.face===face)){const x=(door.axis===0?(door.u-la[0])/du:(door.v-la[1])/dv)*len,s=Math.max(0,x-door.width/2),e=Math.min(len,x+door.width/2);if(e>s+.15){openings=openings.filter(q=>q.e<s-.1||q.s>e+.1);openings.push({s,e,bottom:door.sill,top:3.03,door:true});doorIntervals.push([s,e]);}}
 openings.sort((a,b)=>a.s-b.s);let cursor=0;for(const q of openings){panel(cursor,q.s,base,base+3.2);panel(q.s,q.e,base,q.bottom);panel(q.s,q.e,q.top,base+3.2);const x=(q.s+q.e)/2,w=q.e-q.s,h=q.top-q.bottom,y=(q.top+q.bottom)/2;for(const xx of[q.s,q.e])b.box(xx,y,-setback-.2,.055,h,.40,C.frame,24);for(const yy of[q.bottom,q.top])b.box(x,yy,-setback-.2,w,.055,.40,C.frame,24);b.box(x,y,-setback-.43,w-.1,h-.1,.055,q.door?C.door:C.glass,5);for(const xx of[x-w*.24,x+w*.24])b.box(xx,y,-setback-.385,.05,h,.065,C.frame,24);b.box(x,q.top-.45,-setback-.385,w,.055,.065,C.frame,24);cursor=q.e;}panel(cursor,len,base,base+3.2);
 if(balcony){let bands=[[0,len]];for(const cut of doorIntervals)bands=bands.flatMap(([s,e])=>[[s,Math.min(e,cut[0])],[Math.max(s,cut[1]),e]]).filter(([s,e])=>e>s);for(const [s,e] of bands){b.box((s+e)/2,base+.12,-.55,e-s,.22,1.1,C.frame,24);b.box((s+e)/2,base+.70,-.075,e-s,.94,.15,C.frame,24);b.box((s+e)/2,base+1.20,-.05,e-s,.06,.20,'#c3ccc0',24);for(const [ps,pe] of positions){const end=pe+.50;if(end>s&&end<e)b.box(end,base+1.72,-.55,.13,2.98,1.1,C.frame,24);}}}else b.box(len/2,base+3.1,.03,len,.16,.18,C.frame,24);
 }b.box(len/2,19.30,.12,len,.24,.52,C.frame,24);
 }));}
 b.local(O[0],0,O[1],R,()=>{
 for(const u of stairCentres)group('north-stair-'+u,()=>{for(const x of[u-stairWidth/2,u+stairWidth/2])b.box(x,9.6,-.57,.10,19.2,1.15,C.wall,24);b.box(u,19.25,-.57,stairWidth,.18,1.25,C.frame,24);for(let fl=0;fl<6;fl++){const base=fl*3.2,lo=fl===0?.3:base+1.2,hi=fl===0?3.03:base+2.35,w=fl===0?1.9:1.1,c=fl===5?C.frame:C.wall;for(const side of[-1,1])b.box(u+side*(stairWidth+w)/4,base+1.6,-1.15,(stairWidth-w)/2,3.2,.09,c,24);b.box(u,(base+lo)/2,-1.15,w,lo-base,.09,c,24);b.box(u,(hi+base+3.2)/2,-1.15,w,base+3.2-hi,.09,c,24);b.box(u,(lo+hi)/2,-.95,w-.1,hi-lo-.1,.05,C.glass,5);for(const x of[u-w/2,u+w/2])b.box(x,(lo+hi)/2,-1.08,.055,hi-lo,.22,C.frame,24);}});
 for(const q of entrances)group('entrance-'+q.name,()=>{const w=q.width,s=q.outward;if(q.name==='main-south'){b.box(q.u,.3,q.v+.30,w+.35,.6,2.8,C.stone,24);for(let k=0;k<4;k++){const h=.15*(k+1);b.box(q.u,h/2,q.v+3.4-k*.5,w+.35,h,.51,C.stone,24);}}else if(q.axis===1){b.box(q.u+s*.35,.15,q.v,.7,.3,w+.2,C.stone,24);b.box(q.u+s*.9,.075,q.v,.4,.15,w+.2,C.stone,24);}else{b.box(q.u,.15,q.v+s*.35,w+.2,.3,.7,C.stone,24);b.box(q.u,.075,q.v+s*.9,w+.2,.15,.4,C.stone,24);}});
 });
 return{strategy:'building038-v46',floors:6,basementFloors:2,sourceOutline:true,southBalconies:true,northStairProjections:2,entranceCount:5,groundHallOnly:true,heightMeasured:false,southCanopyVerified:false,southCanopyPlaced:false,eastFacadeVerified:false,photoEndDirectionVerified:false};
}
A.render=function(b,f,add){return f.properties.id===ID?render(b,f,add):previous(b,f,add);};Y.Building038={id:ID,render,world,local,pieces,heights:H,entrances};
})(YY);
