(function(Y){'use strict';const M=Y.M;
class Geometry{
 constructor(){this.v=[]}
 vertex(p,n,uv=[0,0]){this.v.push(...p,...n,...uv)}
 tri(a,b,c,uvs=[[0,0],[1,0],[1,1]],norms){const n=M.norm(M.cross(M.sub(b,a),M.sub(c,a)));this.vertex(a,norms?norms[0]:n,uvs[0]);this.vertex(b,norms?norms[1]:n,uvs[1]);this.vertex(c,norms?norms[2]:n,uvs[2]);return this}
 quad(a,b,c,d,normal){let ns=normal?[normal,normal,normal]:undefined;this.tri(a,b,c,[[0,0],[1,0],[1,1]],ns);this.tri(a,c,d,[[0,0],[1,1],[0,1]],ns);return this}
}
const Geo={Geometry,
 box(){let g=new Geometry(),n=.5;g.quad([-n,-n,n],[n,-n,n],[n,n,n],[-n,n,n]);g.quad([n,-n,-n],[-n,-n,-n],[-n,n,-n],[n,n,-n]);g.quad([-n,-n,-n],[-n,-n,n],[-n,n,n],[-n,n,-n]);g.quad([n,-n,n],[n,-n,-n],[n,n,-n],[n,n,n]);g.quad([-n,n,n],[n,n,n],[n,n,-n],[-n,n,-n]);g.quad([-n,-n,-n],[n,-n,-n],[n,-n,n],[-n,-n,n]);return g},
 plane(){return new Geometry().quad([-.5,-.5,0],[.5,-.5,0],[.5,.5,0],[-.5,.5,0])},
 cylinder(n=12,top=1){let g=new Geometry();for(let i=0;i<n;i++){let a=i/n*Math.PI*2,b=(i+1)/n*Math.PI*2,p=[Math.cos(a),0,Math.sin(a)],q=[Math.cos(b),0,Math.sin(b)],r=[q[0]*top,1,q[2]*top],s=[p[0]*top,1,p[2]*top];g.quad(q,p,s,r);g.tri([0,0,0],p,q);g.tri([0,1,0],r,s)}return g},
 sphere(n=10,m=6,rough=0){let g=new Geometry();const p=(a,b)=>{let k=1+rough*Math.sin(a*5+Math.cos(b*6))*Math.sin(b);return[k*Math.sin(b)*Math.cos(a),k*Math.cos(b),k*Math.sin(b)*Math.sin(a)]};for(let i=0;i<n;i++)for(let j=0;j<m;j++){let a=i/n*Math.PI*2,c=(i+1)/n*Math.PI*2,b=j/m*Math.PI,d=(j+1)/m*Math.PI,A=p(a,b),B=p(c,b),C=p(c,d),D=p(a,d);g.tri(A,B,C,undefined,[M.norm(A),M.norm(B),M.norm(C)]);g.tri(A,C,D,undefined,[M.norm(A),M.norm(C),M.norm(D)])}return g},
 roof(ridge=.62){let g=new Geometry(),N=10,W=12;const f=(t,u,side)=>{let half=.5*(1-t)+ridge*.5*t;return[u*half,Math.pow(t,1.55)*.93+.075*Math.pow(Math.abs(u),7)*Math.pow(1-t,2),side*.5*(1-t)]};for(let side of [-1,1])for(let i=0;i<W;i++)for(let j=0;j<N;j++){let u=-1+2*i/W,v=-1+2*(i+1)/W,t=j/N,s=(j+1)/N;let a=f(t,u,side),b=f(t,v,side),c=f(s,v,side),d=f(s,u,side);if(side===1)g.quad(a,b,c,d);else g.quad(b,a,d,c)}for(let side of [-1,1])for(let i=0;i<N;i++)for(let j=0;j<N;j++){let f2=(t,u)=>[side*(.5*(1-t)+ridge*.5*t),Math.pow(t,1.55)*.93+.075*Math.pow(Math.abs(u),7)*Math.pow(1-t,2),u*.5*(1-t)],a=f2(i/N,-1+2*j/N),b=f2(i/N,-1+2*(j+1)/N),c=f2((i+1)/N,-1+2*(j+1)/N),d=f2((i+1)/N,-1+2*j/N);if(side===1)g.quad(b,a,d,c);else g.quad(a,b,c,d)}return g},
 pagoda(n=8){let g=new Geometry();const rings=[[1,.1],[.99,0],[.88,-.03],[.78,.16],[.59,.57],[.43,.95]];for(let k=0;k<rings.length-1;k++)for(let i=0;i<n;i++){let a=(i/n+.0625)*2*Math.PI,b=((i+1)/n+.0625)*2*Math.PI,[r,y]=rings[k],[R,Y]=rings[k+1];g.quad([Math.cos(b)*r,y,Math.sin(b)*r],[Math.cos(a)*r,y,Math.sin(a)*r],[Math.cos(a)*R,Y,Math.sin(a)*R],[Math.cos(b)*R,Y,Math.sin(b)*R])}return g},
 polygon(points,y=0){let g=new Geometry();let ids=points.map((_,i)=>i),area=points.reduce((a,p,i)=>a+p[0]*points[(i+1)%points.length][1]-points[(i+1)%points.length][0]*p[1],0);if(area<0)ids.reverse();let guard=0;while(ids.length>2&&guard++<points.length*points.length){let found=false;for(let k=0;k<ids.length;k++){let a=points[ids[(k+ids.length-1)%ids.length]],b=points[ids[k]],c=points[ids[(k+1)%ids.length]];if((b[0]-a[0])*(c[1]-b[1])-(b[1]-a[1])*(c[0]-b[0])<=0)continue;let inside=false;for(let j of ids){let p=points[j];if(p===a||p===b||p===c)continue;let s=(q,r)=> (r[0]-q[0])*(p[1]-q[1])-(r[1]-q[1])*(p[0]-q[0]);if(s(a,b)>=0&&s(b,c)>=0&&s(c,a)>=0){inside=true;break}}if(inside)continue;g.tri([a[0],y,a[1]],[c[0],y,c[1]],[b[0],y,b[1]]);ids.splice(k,1);found=true;break}if(!found)break}return g},
 ribbon(points,width,y=.23,closed=false){let g=new Geometry(),e=[];for(let i=0;i<points.length;i++){let prev=points[closed?(i-1+points.length)%points.length:Math.max(i-1,0)],next=points[closed?(i+1)%points.length:Math.min(i+1,points.length-1)],d=M.norm([next[0]-prev[0],next[1]-prev[1]]);e.push([[points[i][0]-d[1]*width/2,y,points[i][1]+d[0]*width/2],[points[i][0]+d[1]*width/2,y,points[i][1]-d[0]*width/2]])}for(let i=0;i<(closed?points.length:points.length-1);i++){let j=(i+1)%points.length;g.quad(e[i][0],e[j][0],e[j][1],e[i][1],[0,1,0])}return g},
 torus(n=16,m=6){let g=new Geometry();const p=(i,j)=>{let a=i/n*Math.PI*2,b=j/m*Math.PI*2,r=1+.12*Math.cos(b);return[r*Math.cos(a),r*Math.sin(a),.12*Math.sin(b)]};for(let i=0;i<n;i++)for(let j=0;j<m;j++)g.quad(p(i,j),p(i+1,j),p(i+1,j+1),p(i,j+1));return g}
};Y.Geo=Geo;
})(YY);
