import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';

export function modelGroup(model, referenceOrigin=model.origin){
 const root=new THREE.Group();root.position.fromArray(model.origin.map((v,i)=>v-referenceOrigin[i]));const nodes=new Map();
 for(const n of model.nodes){let object;
  if(n.type==='group')object=new THREE.Group();
  else{let geometry;if(n.type==='box')geometry=new THREE.BoxGeometry(...n.size);else if(n.type==='cylinder')geometry=new THREE.CylinderGeometry(n.radius,n.radius,n.height,n.segments);else if(n.type==='mesh'){geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(n.vertices.flat(),3));geometry.setIndex(n.indices.flat());geometry.computeVertexNormals()}else throw Error('不支持的几何类型');
   object=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:n.color,roughness:.78,metalness:0,side:THREE.DoubleSide}));object.castShadow=true;object.receiveShadow=true;}
  object.position.fromArray(n.position);object.rotation.y=n.rotation;object.name=n.id;(n.parent_id?nodes.get(n.parent_id):root).add(object);nodes.set(n.id,object);
 }
 return root;
}

export function createView(container){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#e7ece2');const camera=new THREE.PerspectiveCamera(42,1,.1,5000);const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;renderer.shadowMap.enabled=true;container.append(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;const hemisphere=new THREE.HemisphereLight(0xf5f6ed,0x75836b,2.5);scene.add(hemisphere);const sun=new THREE.DirectionalLight(0xfff7e3,3.3);sun.position.set(45,80,40);scene.add(sun);let group;
 const resize=()=>{const w=container.clientWidth||960,h=container.clientHeight||640;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};resize();const observer=new ResizeObserver(resize);observer.observe(container);let stop=false;
 function frame(){if(stop)return;requestAnimationFrame(frame);controls.update();renderer.render(scene,camera)}frame();
 return {renderer,scene,camera,controls,load(models){if(group){scene.remove(group);group.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose()})}group=new THREE.Group();const origin=models[0].origin;models.forEach(m=>group.add(modelGroup(m,origin)));scene.add(group);const bounds=new THREE.Box3().setFromObject(group),size=new THREE.Vector3(),center=new THREE.Vector3();bounds.getSize(size);bounds.getCenter(center);if(![...size,...center].every(Number.isFinite)||Math.max(...size)>800)throw Error('模型整体边界异常，请检查层级与坐标');const extent=Math.max(size.x,size.y,size.z,2);camera.near=Math.max(.01,extent/3000);camera.far=extent*30;camera.position.copy(center).add(new THREE.Vector3(extent*1.1,extent*.75,extent*1.35));camera.updateProjectionMatrix();controls.target.copy(center);controls.minDistance=extent*.02;controls.maxDistance=extent*12;controls.update();renderer.render(scene,camera);const triangles=models.reduce((sum,m)=>sum+m.nodes.reduce((a,n)=>a+(n.type==='box'?12:n.type==='cylinder'?n.segments*4:n.type==='mesh'?n.indices.length:0),0),0);return {triangles,bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},draw_calls:renderer.info.render.calls}},dispose(){stop=true;observer.disconnect();controls.dispose();renderer.dispose()}};
}

window.PKU_RENDER_MODEL=async model=>{const view=createView(document.querySelector('#check-stage'));const stats=view.load([model]);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));window.PKU_RENDER_RESULT=stats;return stats};

export async function mountPreview({root,api,esc,heading,query,me}){
 const sub=query.get('submission'),revision=query.get('revision'),place=query.get('place');let model,record,all=[];
 if(sub){record=await api('/submissions/'+sub);model=record.model}
 else if(revision){record=await api('/models/'+revision);model=record.model}
 else if(place){all=(await api('/models?place_id='+encodeURIComponent(place))).models;if(!all.length)throw Error('这里还没有发布的社区模型');model=(await api(all[0].url.replace('/api/v1',''))).model}
 else throw Error('请选择一个模型版本或提交');
 if(!all.length)all=(await api('/models?place_id='+encodeURIComponent(model.place_id))).models;
 const floors=[...new Set(all.filter(m=>['floor','room'].includes(m.space)).map(m=>m.floor))];
 root.innerHTML=`<div class="wrap">${heading(sub?'候选模型预览':'局部模型',esc(model.title),'提供到哪里，就建设到哪里。拖动旋转，滚动缩放；没有资料的部分不会自动补齐。')}<div class="toolbar"><span class="pill">${sub?'候选成果':'已发布'} · ${esc(record.verification||'待实地核对')}</span><a class="button secondary" href="/place/?id=${encodeURIComponent(model.place_id)}">地点档案 ↗</a></div>${floors.length?`<div class="space-tabs"><button data-space="part" class="active">当前部位</button>${floors.map(f=>`<button data-space="floor" data-floor="${esc(f)}">${esc(f)}</button>`).join('')}</div>`:''}<div class="preview-stage" id="preview-stage"><div class="preview-badge">${esc(model.floor||'局部空间')} · 米制坐标</div></div><div class="layout"><section class="panel"><h3>资料依据与不确定性</h3>${(record.verification_records||[]).map(v=>`<p class="notice">核对记录 · ${esc(v.actor)}：${esc(v.note)}</p>`).join('')}${model.evidence.map(e=>`<p class="muted"><span class="pill">${e.certainty==='observed'?'观察依据':'估计项'}</span> ${esc(e.supports)}</p>`).join('')}${model.uncertainties.length?`<ul class="muted">${model.uncertainties.map(u=>`<li>${esc(u)}</li>`).join('')}</ul>`:'<p class="muted">贡献者未填写额外不确定项，仍需实地核对。</p>'}${model.base_revision?'<button class="button secondary" id="compare">查看修改前的社区版本</button>':'<p class="muted small">这是该部位的首个社区模型，可到校园中对照原有底模。</p>'}<div class="actions"><a id="model-feedback" class="button secondary" href="/feedback/?place=${encodeURIComponent(model.place_id)}">指出这处模型的问题</a>${record.pr_url?`<a class="button secondary" href="${esc(record.pr_url)}" target="_blank" rel="noopener">GitHub 修改记录 ↗</a>`:''}</div></section><aside class="panel aside"><h3>模型状态</h3><p id="model-status">${esc(({preview_queued:'等待生成预览',preview_checking:'正在生成预览',preview_ready:'预览已就绪',queued:'等待检查',checking:'正在检查',waiting_setup:'等待维护者配置发布',pr_open:'正在处理发布',published:'已发布',failed:'检查未通过',changes_requested:'需要修正',withdrawn:'资料已撤回'})[record.state]||'已发布')}。技术检查不等于现实准确性确认。</p><p id="render-stats"></p>${sub?'<button id="refresh-preview" class="button secondary">刷新检查结果</button>':''}</aside></div></div>`;
 const view=createView(root.querySelector('#preview-stage'));const stats=view.load([model]);root.querySelector('#render-stats').textContent=`当前预览只包含这个局部空间。参考照片可在你认领的任务资料中对照。`;
 if(root.querySelector('#compare')){let before=false;root.querySelector('#compare').onclick=async e=>{before=!before;try{view.load([before?(await api('/models/'+model.base_revision)).model:model]);e.target.textContent=before?'返回修改后的候选模型':'查看修改前的社区版本'}catch(err){e.target.textContent=err.message}}}
 root.querySelectorAll('[data-space]').forEach(b=>b.onclick=async()=>{try{const selection=b.dataset.space==='part'?[model]:await Promise.all(all.filter(m=>m.floor===b.dataset.floor).map(async m=>(await api(m.url.replace('/api/v1',''))).model));view.load(selection);root.querySelectorAll('[data-space]').forEach(x=>x.classList.toggle('active',x===b))}catch(e){root.querySelector('#model-status').textContent=e.message}});
 root.querySelector('#model-feedback').onclick=()=>{view.renderer.render(view.scene,view.camera);sessionStorage.setItem('pku-feedback-context',JSON.stringify({place_id:model.place_id,part:model.title,floor:model.floor,revision:record.content_hash||record.revision||revision,model_revisions:{[model.part_id]:record.content_hash||record.revision||revision},view:{eye:view.camera.position.toArray(),target:view.controls.target.toArray()},screenshot:view.renderer.domElement.toDataURL('image/jpeg',.85)}))};if(sub)root.querySelector('#refresh-preview').onclick=()=>location.reload();
}
